### ISSUE TITLE
Crash after uncaught error

### ISSUE THREAD

**Issue by ward** [ward/irc-butler#33]
Not exactly sure what the cause is. This was in the console:

```
25 May 00:11:03 - SEND: PING 5364
25 May 00:11:11 - Connection got "close" event
25 May 00:11:11 - Disconnected: reconnecting
25 May 00:11:11 - Waiting 2000ms before retrying
25 May 00:11:14 - Sending irc NICK/USER
25 May 00:11:14 - SEND: NICK irc-butler
25 May 00:11:15 - SEND: USER butler 8 * :Your butler for a nice IRC experience
25 May 00:11:29 - SEND: PING 5365
IRCBUTLERDIRECTORY/node_modules/irc/lib/irc.js:849
                        throw err;
                        ^

Error: Uncaught, unspecified "error" event. ([object Object])
    at Client.emit (events.js:163:17)
    at Client.<anonymous> (IRCBUTLERDIRECTORY/node_modules/irc/lib/irc.js:643:26)
    at emitOne (events.js:96:13)
    at Client.emit (events.js:188:7)
    at iterator (IRCBUTLERDIRECTORY/node_modules/irc/lib/irc.js:846:26)
    at Array.forEach (native)
    at Socket.handleData (IRCBUTLERDIRECTORY/node_modules/irc/lib/irc.js:841:15)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
```

**Comment by ward** [comment]
Another one

```
18 Jun 15:23:46 - rcv40 #reddit-soccer !games uefa
18 Jun 15:23:46 - Cache invalidated, running update.
undefined:1



SyntaxError: Unexpected end of JSON input
    at Object.parse (native)
    at parseLivescoreJSON (/home/ward/node-irc-butler/plugins/football-livescore.js:82:18)
    at κ (/home/ward/node-irc-butler/plugins/football-livescore.js:125:7)
    at IncomingMessage.<anonymous> (/home/ward/node-irc-butler/plugins/football-livescore.js:72:7)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

Woops

**Comment by ward** [comment]
That one is caught now^
